apiVersion: v1
kind: Namespace
metadata:
  name: xenon-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xenon-config
  namespace: xenon-app
  labels:
    component: frontend
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>This is Xenon App</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        # Serve the homepage at root
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: xenon-dataset-config
  namespace: xenon-app
  labels:
    component: dataset
data:
  dataset.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>This is the page for Xenon App Dataset</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        # Serve the /products page using alias
        location /dataset {
          alias /usr/share/nginx/html/dataset.html;
        }
      }
    }
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: xenon-deployment
  namespace: xenon-app
  labels:
    app: nginx
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: xenon-config
      - name: nginx-conf-volume
        configMap:
          name: xenon-config
          items:
          - key: nginx.conf
            path: nginx.conf
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: xenon-dataset-deployment
  namespace: xenon-app
  labels:
    app: nginx
    component: dataset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      component: dataset
  template:
    metadata:
      labels:
        app: nginx
        component: dataset
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: xenon-dataset-config
      - name: nginx-conf-volume
        configMap:
          name: xenon-dataset-config
          items:
          - key: nginx.conf
            path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: xenon-service
  namespace: xenon-app
  labels:
    component: frontend
spec:
  selector:
    app: nginx
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: xenon-dataset-service
  namespace: xenon-app
  labels:
    component: dataset
spec:
  selector:
    app: nginx
    component: datasets
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


