{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-gateway.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- end }}
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{ toYaml .Values.service.loadBalancerSourceRanges | nindent 2 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "nginx-gateway.selectorLabels" . | nindent 4 }}
  ports:
    {{- if .Values.service.ports }}
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if eq $.Values.service.type "NodePort" }}
      {{- if eq .name "http" }}
      nodePort: {{ $.Values.service.nodePort | default 32000 }}
      {{- end }}
      {{- end }}
      protocol: {{ .protocol }}
    {{- end }}
    {{- else }}
    - name: http
      port: 80
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 32000 }}
      {{- end }}
      protocol: TCP
    {{- end }}
{{- end }}
