---
# Create the frontend namespace
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
# Create the API namespace
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
# Create the payment namespace
apiVersion: v1
kind: Namespace
metadata:
  name: payment
---
# ConfigMap for frontend nginx with custom /cart and /orders pages using alias
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: frontend
  labels:
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hey! I am the website frontend</h1>
    </body>
    </html>
  cart.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>You are accessing the cart page</h1>
    </body>
    </html>
  orders.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>You are accessing the orders page</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }

        location /cart {
          alias /usr/share/nginx/html/cart.html;
        }

        location /orders {
          alias /usr/share/nginx/html/orders.html;
        }
      }
    }
---
# ConfigMap for API nginx with custom /api page and /api/inventory
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: api
  labels:
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hey I am the backend API</h1>
    </body>
    </html>
  inventory.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>You are accessing the inventory page</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        location /api {
          alias /usr/share/nginx/html/index.html;
        }

        location /api/inventory {
          alias /usr/share/nginx/html/inventory.html;
        }
      }
    }
---
# ConfigMap for payment nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: payment
  labels:
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hey I am the payment API</h1>
    </body>
    </html>
---
# Deployment for frontend nginx with labels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
  labels:
    app: nginx
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        component: frontend
        env: production
        project: ecommerce-platform
        version: "1.0.0"
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
---
# Service for frontend nginx
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  labels:
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
spec:
  selector:
    app: nginx
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# Deployment for API nginx with labels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api
  labels:
    app: nginx
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        component: frontend
        env: production
        project: ecommerce-platform
        version: "1.0.0"
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
---
# Service for API nginx
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
spec:
  selector:
    app: nginx
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
# Deployment for payment nginx with labels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: payment
  labels:
    app: nginx
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        component: frontend
        env: production
        project: ecommerce-platform
        version: "1.0.0"
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
---
# Service for payment nginx
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
  labels:
    component: frontend
    env: production
    project: ecommerce-platform
    version: "1.0.0"
spec:
  selector:
    app: nginx
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
