apiVersion: v1
kind: Namespace
metadata:
  name: pluto-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pluto-config
  namespace: pluto-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>This is Pluto App</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        # Serve the homepage at root
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluto-deployment
  namespace: pluto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pluto
  template:
    metadata:
      labels:
        app: pluto
    spec:
      containers:
      - name: pluto-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: pluto-app-config
      - name: nginx-conf-volume
        configMap:
          name: pluto-app-config
          items:
          - key: nginx.conf
            path: nginx.conf

---

apiVersion: v1
kind: Service
metadata:
  name: pluto-service
  namespace: pluto-app
spec:
  type: NodePort
  selector:
    app: pluto-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
